# name: Jest Tests
# on:
#   push:
#   pull_request:
#     types: [opened]
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v2
#       with:
#         node-version: '14.x'
#     - name: Install dependencies
#       run: yarn install
#     - name: Run Jest Tests
#       run: yarn test unit
    
